apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-frontend-deployment
  labels:
    app: bloom-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloom-frontend-app
  template:
    metadata:
      labels:
        app: bloom-frontend-app
    spec:
      containers:
      - name: bloom-frontend-container
        image: 705532379788.dkr.ecr.ap-southeast-1.amazonaws.com/bloom-frontend:latest
        resources:
          requests: 
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 60m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bloom-frontend-service
  labels:
    app: bloom-frontend-app
spec:
  type: NodePort
  selector:
    app: bloom-frontend-app
  ports:
    - port: 80
      targetPort: 80