apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-frontend-deployment
  labels:
    app: bloom-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloom-frontend-app
  template:
    metadata:
      labels:
        app: bloom-frontend-app
    spec:
      containers:
        - name: bloom-frontend-container
          image: 705532379788.dkr.ecr.ap-southeast-1.amazonaws.com/bloom-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 60m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bloom-frontend-service
  labels:
    app: bloom-frontend-app
spec:
  type: ClusterIP
  selector:
    app: bloom-frontend-app
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloom-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: sharedalbgroup
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:705532379788:certificate/b31947e9-19d2-4950-8d28-8a4067182296,
                                              arn:aws:acm:ap-southeast-1:705532379788:certificate/1cec5769-42e3-4e77-bd38-c53b7c774c8d
spec:
  ingressClassName: alb
  rules:
    - host: bloomspectrum.my
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bloom-frontend-service
                port:
                  number: 80
    - host: www.bloomspectrum.my
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bloom-frontend-service
                port:
                  number: 80